@startuml
package SorpresaSorpresa{
Class Demo
Class TestMacOSFactory
package SorpresaSorpresa.app{
    Class Appplication
    }
package SorpresaSorpresa.buttons{
    Interface Button
    Class ButtonWindows
    Class ButtonMac
}
package SorpresaSorpresa.checkbox{
    Interface Checkbox
    Class CheckboxWindows
    Class CheckboxMac
}
package SorpresaSorpresa.factories{
    Interface GUIFactory
    Class WindowsFactory
    Class MacOSFactory
}
}
Checkbox <|-- CheckboxWindows
Checkbox <|-- CheckboxMac
Button <|-- ButtonWindows
Button <|-- ButtonMac
GUIFactory <|-- WindowsFactory
GUIFactory <|-- MacOSFactory

@enduml